site_name: Uncrustify Config Examples

use_directory_urls: false

nav:
    - Home: index.md
    - Spacing:
        - 'sp_angle_paren': 'spacing_options/sp_angle_paren.md'
        - 'sp_angle_word': 'spacing_options/sp_angle_word.md'
        - 'sp_assign': 'spacing_options/sp_assign.md'
        - 'sp_brace_else': 'spacing_options/sp_brace_else.md'
        - 'sp_cpp_lambda_assign': 'spacing_options/sp_cpp_lambda_assign.md'
        - 'sp_cpp_lambda_paren': 'spacing_options/sp_cpp_lambda_paren.md'
        - 'sp_else_brace': 'spacing_options/sp_else_brace.md'
        - 'sp_inside_fparens': 'spacing_options/sp_inside_fparens.md'
        - 'sp_not': 'spacing_options/sp_not.md'
    - Newline:
        - 'nl_brace_else': 'newline_options/nl_brace_else.md'
        - 'nl_before_block_comment': 'newline_options/nl_before_block_comment.md'
        - 'nl_catch_brace': 'newline_options/nl_catch_brace.md'
        - 'nl_else_brace': 'newline_options/nl_else_brace.md'
        - 'nl_elseif_brace': 'newline_options/nl_elseif_brace.md'
        - 'nl_for_brace': 'newline_options/nl_for_brace.md'
        - 'nl_if_brace': 'newline_options/nl_if_brace.md'
        - 'nl_if_leave_one_liners': 'newline_options/nl_if_leave_one_liners.md'
        - 'nl_max': 'newline_options/nl_max.md'
        - 'nl_max_blank_in_func': 'newline_options/nl_max_blank_in_func.md'
        - 'nl_multi_line_cond': 'newline_options/nl_multi_line_cond.md'
        - 'nl_switch_brace': 'newline_options/nl_switch_brace.md'
    - Other options:
        - 'cmt_width': 'other_options/cmt_width.md'
        - 'code_width': 'other_options/code_width.md'
        - 'mod_full_brace_if': 'other_options/mod_full_brace_if.md'
        - 'mod_full_brace_for': 'other_options/mod_full_brace_for.md'

    - About: about.md

theme: spacelab
