site_name: Uncrustify Config Examples

use_directory_urls: false

nav:
    - Home: index.md
    - Spacing:
        - 'sp_brace_else': 'spacing_options/sp_brace_else.md'
        - 'sp_cpp_lambda_assign': 'spacing_options/sp_cpp_lambda_assign.md'
        - 'sp_cpp_lambda_paren': 'spacing_options/sp_cpp_lambda_paren.md'
        - 'sp_not': 'spacing_options/sp_not.md'
    - Newline:
        - 'nl_brace_else': 'newline_options/nl_brace_else.md'
        - 'nl_else_brace': 'newline_options/nl_else_brace.md'
        - 'nl_if_brace': 'newline_options/nl_if_brace.md'
    - Other options:
        - 'cmt_width': 'other_options/cmt_width.md'
        - 'code_width': 'other_options/code_width.md'

    - About: about.md

theme: spacelab
