site_name: Uncrustify Config Examples

use_directory_urls: false

nav:
    - "<": 'index.md'
    - Options: options_list.md
    - About: about.md

theme: spacelab

google_analytics: ['UA-153878605-1', 'beardog-ukr.github.io/uncrustify-config-examples/']
